dsternlicht/RESTool

src/app/utils/url.utils.ts

This allows the config.json to use URLs like:
* `//restool-sample-app.herokuapp.com/api/contacts/:id`
* `/api/contacts/:id`

Support relative URLs in config file

---

README.md
src/app/services/requests.service.ts
src/config-sample.json

This makes the error message a little cleaner when our API returns details as part of a DTO.
The server referenced in config-sample.json returns an error property, so you can try this out pretty easily.

Add optional errorMessageDataPath to config.json

---

README.md
src/app/services/requests.service.ts

Here's a new feature that lets you redirect a user to an external site when they are not authenticated for the API they're calling.
I didn't want the return url to be required, and need to support hard-coded query parameters in the url, so I've also enhanced the `buildUrl` function a bit too.

Add unauthorized redirect url

---

src/app/services/requests.service.ts

Thanks for upgrading angular.
Unfortunately the upgrade broke the error handler. Here is a fix.

Fix 'Observable.throw is not a function' in handleError

---

src/app/app.module.ts
src/app/components/main-view/main-view.component.ts
src/app/services/configuraion.service.ts

I found another small issue after the upgrade. It shows up if you navigate to the app directly without a `#/page` specified.
I also discovered that the `APP_BASE_HREF` registration isn't necessary any more, so I'm dropping that too.

Fix error: Observable.of not defined

---

README.md
src/app/components/input/field-input.component.html
src/app/components/input/field-input.component.ts
src/app/components/main-view/get/get.component.html
src/app/components/main-view/get/get.component.ts
src/app/components/main-view/post/post.component.html
src/app/components/main-view/post/post.component.ts
src/app/components/main-view/put/put.component.html
src/app/components/main-view/put/put.component.ts
src/app/services/config.model.ts

I switched the query parameters on the get page to use the same input-field component as the post and put pages, allowing more logic to be shared across all the different views. This brought select and checkbox types to the post/put fields. I also added the `optionSource` property so the select boxes can pull their data dynamically from an arbitrary api.
I updated the readme for both changes. Because the code is shared between the two, I wanted both queryParams and fields to be documented in only one place. There are a couple options that only work for one or the other, so I had to add notes for those.
I've also fixed a minor layout issue when a page doesn't have a description.

Add data-driven select box for query parameters and post / put pages

---

src/app/components/main-view/get/get.component.ts
src/app/components/main-view/main-view.component.ts
src/app/components/main-view/post/post.component.ts
src/app/components/main-view/put/put.component.ts
src/environments/environment.prod.ts
src/environments/environment.ts

With some of our larger data sets, quite a bit of data is being dumped to the console window. This change keeps the functionality for development builds, and makes it easy for someone to add back when making a production build (just edit environment.prod.ts).

Prevent logging of data sent/received from API in production builds

---

README.md
src/app/components/input/field-input.component.html
src/app/components/input/field-input.component.scss
src/app/components/main-view/get/get.component.ts
src/app/components/main-view/post/post.component.html
src/app/components/main-view/post/post.component.ts
src/app/components/main-view/put/put.component.html
src/app/components/main-view/put/put.component.ts
src/config-sample.json
src/styles/_purecss.scss

Here is a bunch of small changes all bundled together:
* support both integer and float-point number as different types
* handle explicit 0 and null values, empty values are now transmitted as null
* rename default value property on query params to `default` for consistency, but preserve support for old name `value`
* support required fields for post and put forms
* support read-only fields for put form

Enhance value handling

---

src/app/components/input/field-input.component.ts
src/app/components/main-view/post/post.component.html
src/app/components/main-view/post/post.component.ts
src/app/components/main-view/put/put.component.html
src/app/components/main-view/put/put.component.ts

This allows the URL for an on option source to contain parameters, and those parameters can come from other fields on the same form. This helps when you have a reference to hierarchical data and need to filter the options in a select box.

Allow for dynamic parameters in option source url

---

README.md
src/app/components/input/array-input.component.html
src/app/components/input/array-input.component.scss
src/app/components/input/array-input.component.ts
src/app/components/input/field-input.component.html
src/app/components/input/field-input.component.ts
src/app/components/main-view/main-view.module.ts
src/app/components/main-view/post/post.component.ts
src/app/components/main-view/put/put.component.ts

This makes the array type render as multiple controls, with the control for the type specified in `arrayType`.
I didn't spend a lot of effort making it pretty, but I don't think it looks bad:
I've also included a fix for the readonly feature: it now hides the placeholder text for readonly fields.

Multiple inputs for array type

---

README.md
src/app/components/main-view/get/get.component.html
src/app/components/main-view/get/get.component.scss
src/app/components/main-view/get/get.component.ts
src/app/components/main-view/main-view.module.ts
src/app/components/main-view/row-filter.pipe.ts
src/config-sample.json

This PR allows very simple client-side text filtering by certain fields. Any fields configured with `"filterable": true` are included (by calling .toString on the value). The control is shown on a page if at least 1 field is filterable.
I am very inexperienced with CSS so happy for any suggestions to tidy up the layout.
Example:

Allow simple client-side text filtering

---

README.md
src/app/components/input/field-input.component.html
src/app/components/input/field-input.component.scss

This PR adds support for a password type.
I am also fixing a minor regression I noticed: required fields will have their labels bolded. It looks like it dropped by accident as part of https://github.com/dsternlicht/RESTool/pull/41

Add password type

---

README.md
src/app/components/main-view/put/put.component.ts

Currently only values retrieved in the GET of an object can be used as parameters in the URL of a PUT
* Added `useInUrl` as boolean option on a field object in a PUT method.
* Effectively allows a user to define a value that can then be used as a parameter in the URL
No worries if you don't want this change either 😃  Could be helpful for some

Added useInUrl field option

---

src/app/components/main-view/post/post.component.ts

I have an endpoint that needs one of the properties from the post page to go into the URL. This changes makes the post page a little more consistent with the put page.

Allow variable substitution from form details on post pages

---

README.md
src/app/components/main-view/get/get.component.html
src/app/components/main-view/get/get.component.ts
src/app/components/main-view/main-view.component.html
src/app/components/main-view/main-view.component.ts
src/app/components/main-view/put/put.component.html
src/app/components/main-view/put/put.component.ts
src/config-sample.json

> This PR contains is the same as https://github.com/dsternlicht/RESTool/pull/53 but has the requested changes 
Sadly a lot APIs in the wild are only 90% RESTful. Most people cannot resist the urge to add in a cheeky extra action endpoint. I came across one of these APIs so I made this tweak.
- Add new array attribute on page called `customActions` which is a list of PUT methods. 
- If set a dropdown now appears on the Edit Item dialog to allow the user to select the action they want to perform (endpoint they want to call).
- README and sample-config.json have been updated with instructions and examples
These allow extra endpoints to be added such as `PUT http://website.com/users/:id/disable`

New customActions parameter

---

src/app/components/main-view/main-view.component.html

Looks like a recent feature addition broke some existing functionality.
This PR fixes the bug.
The bug prevents array lists from being displayed. Every other piece of data seems to display correctly.
With this data:
```
{
"Results": [{
"UniqueId": "f2bbedebaf0d43209eda8e38df780cc7",
"Key": "Test",
"ValueType": "PickList",
"PickListValues": ["a", "b", "c"]
}
]
}
```
and this (partial) config. Note: The revelant field is `PickListValues`:
```
"put": {
"url": "/AQUARIUS/Provisioning/v1/tags/:UniqueId",
"fields": [
{"name": "Key", "label": "Key", "type": "text", "required": true},
{"name": "ValueType", "label": "Value Type", "type": "select", "options": [{"value": "None", "display": "None"}, {"value": "PickList", "display": "Pick List"}], "default": "None"},
{"name": "PickListValues", …
```

Bugfix: Restoring broken functionality for array lists

---

src/components/page/page.comp.tsx

Fix for data refresh when lazy-loading pagination is on after a item add/edit/delete.
Missed that one.

Fix for data refresh when lazy-loading pagination is on

---

src/components/page/page.comp.tsx

I think the pagination property should allow to rename variables without being limited to specific names such as page, limit, sortBy and descending.
However, only certain aforementioned names are allowed. In order to solve this problem, I've created this PR.

fix pagination comp

---

.gitignore
src/components/formPopup/formPopup.comp.tsx

This will fix the faulty rendering of empty integer/number fields.
Currently they get rendered like this ...
```
{
"myIntegerField":"",
...
```
... when empty.
Which is wrong, since this is interpreted as a string by most backends.
The JSON-datatype "null" should be used instead (see: [JSON Data Types](https://www.w3schools.com/js/js_json_datatypes.asp)).

Fix integer field handling

---

README.md

The method listing incorrectly included post twice, and did not include delete. This change fixes that.

Method listing corrected to include "delete"

---

package-lock.json
src/common/models/config.model.ts
src/components/app.tsx
src/components/page/page.comp.tsx
src/config/config-sample.ts
src/config/index.ts
src/helpers/data.helpers.ts

A new module, `src/config/index.ts`, exports a function that generates an `IConfig` or `undefined`.
By default, it returns `undefined`, and is ignored.
If you change it to return an object implementing `IConfig` (such as the included example), RESTool will use that as the active configuration.
RESTool is easy to use and can be updated just by deploying a configuration file, but complex configurations are difficult to manage by hand, and cannot be linted by a code editor.
This module allows:
- linting and editor hinting
- use of externally provided data transforms written in typescript
- automatic generation of configuration using arbitrary external functions
This requires using RESTool in dev mode, and deploying updates. See "How to develop", below.
Some config interfaces in …

in tree config and updates to config model optional fields

---

src/components/formPopup/formPopup.comp.tsx

Hi again, 
With my latest change (adding dataTransform to put/post) I introduced a bug where dataTransform will get called twice for custom actions. This PR removes dataTransform from customAction code as it is now handled elsewhere.

Data transform being called twice for custom actions

---

README.md
src/assets/schemas/config.schema.json
src/common/models/config.model.ts
src/components/formPopup/formPopup.comp.tsx
src/components/formPopup/formPopup.scss
src/components/page/page.comp.tsx
src/components/page/page.scss

Hello, when using the tool to create a localized prototype i realized that not all button texts and colors where customizable, so I added some vars to make them customizable.
Color of the add button.
Text and color of the submit button in forms.
See README.md changes for further details.

Made button labels and styles more configurable.

---

README.md
src/assets/schemas/config.schema.json
src/common/models/config.model.ts
src/components/formRow/formRow.comp.tsx
src/services/http.service.ts

This addition to the settings defined in **_"optionSource"_** is aimed at fetching search results according to the keyword typed in the search box. As the search query length >= 3 characters, the new get request will be sent to fetch more results.
> [!TIP]
> By default, a search query alias is defined as `q`. If you need to define another alias, set the new optional **_"optionSource"_** key named **_"queryParamAlias"_** to a desirable value.
```
fields: [
{
name: "bestFriend",
label: "Best Friend",
type: "select-multi",
multi: true,
optionSource: {
url: "https://restool-sample-app.herokuapp.com/api/character",
dataPath: null,
displayPath: "name",
valuePath: "id",
sortBy: ["name"]
}
}
]
```
Searhcing for `Arya` keyword results in the following request URL: …

Feature: multiselect search query

---

README.md
package-lock.json
package.json
src/components/app.tsx
src/components/auth/changePasswortPage/changePasswortPage.comp.tsx
src/components/auth/loginPage/loginPage.comp.tsx
src/components/cards/cards.comp.tsx
src/components/filterField/filterField.comp.tsx
src/components/formPopup/formPopup.comp.tsx
src/components/formRow/formRow.comp.tsx
src/components/navigation/navigation.comp.tsx
src/components/page/page.comp.tsx
src/components/pagination/pagination.comp.tsx
src/components/popup/popup.comp.tsx
src/components/queryParams/queryParams.comp.tsx
src/components/table/table.comp.tsx
src/hooks/usePageTranslation.ts
src/i18n.ts
src/index.tsx
src/locales/en.json

References Issue #271
This pull request implements internalisation using the i18next library.
All labels are moved to the provided i18n file `en.json'.
This deprecates customLabel and page-specific labels like page.title / page.description and field.label.
For backwards compatibility, if these labels are defined in config.js, they will override the i18n files.

Internationalization i18n (Multi Language Support)

---

.vscode/settings.json
README.md
src/components/cards/cards.comp.tsx
src/components/formRow/formRow.comp.tsx
src/components/table/table.comp.tsx

Adds the ability to translate select field values through the i18n system, allowing different display text in UI while maintaining original values for backend communication. Useful for showing localized options in dropdowns and translated values in tables/cards.

Add i18n support for field values in select dropdowns and displays

---

README.md
public/config-sample.js
src/assets/schemas/config.schema.json
src/common/models/config.model.ts
src/components/cards/cards.comp.tsx
src/components/page/page.comp.tsx
src/components/page/page.scss
src/components/table/table.comp.tsx
src/locales/en.json

Allows to define custom FA icons for the add/edit/delete action buttons, respectievly shown in 
- "Add item" button on the top of the page
- Edit + delete icons in cards layout
- Edit + delete icons in table layout
This works in the same way for the `cutomAction' already. 
Defaults to the default icons if no icons are configured in the config.

Custom Icons for post/put/delete action buttons

---

README.md
src/common/models/config.model.ts
src/components/app.scss
src/components/navigation/navigation.comp.tsx
src/components/navigation/navigation.scss
src/locales/en.json

This pull request improves the styling of the navbar by moving the auth-related items (Change Password + Logout) to the bottom of the navbar.
It also adds section labels to the "page" section at the top of the navbar and the "auth" section at the bottom.  These can be translated using i18nfile or removed using i18n to not display them at all.

Positioning of auth-related navbar items + Introducing Navbar section labels

---

README.md
public/config-sample.js
src/assets/schemas/config.schema.json
src/common/models/config.model.ts
src/components/navigation/navigation.comp.tsx
src/components/navigation/navigation.scss

Adds the option to define an icon in the page config, which will be shown in the navigation bar.
If no icon is not defined, navigation remains the same as before:

Add optional icons to page navigation links

---

README.md
src/assets/schemas/config.schema.json
src/common/models/config.model.ts
src/components/app.scss
src/components/app.tsx
src/components/header/header.comp.tsx
src/components/header/header.scss

Adds support for a logo.png in the header (header is hidden if no logo is provided). 
To add the logo, simply a `logo.png` file needs to be present in /src/assets/images.
Also improves README readability with a table of contents.
Let me know what you think 😊

Add option to show logo header

---

README.md
src/components/cards/cards.comp.tsx
src/components/cards/cards.scss
src/components/formRow/formRow.comp.tsx
src/components/formRow/formRow.scss
src/components/table/table.comp.tsx
src/components/table/table.scss
src/locales/en.json

This adds the option to define a help text for individual fields.
The help text can be configured via i18n language files and is displayed differently depending on the layout - below the field names in card layout and as hoverable icons in table layout.

Add optional helptexts for fields

---

src/components/cards/cards.comp.tsx
src/components/formRow/formRow.comp.tsx
src/components/navigation/navigation.comp.tsx
src/components/table/table.comp.tsx

This PR adds CSS classes to various component elements, using encoded field or page names. This makes it easier to apply custom CSS overrides on a per-field or per-page basis.
There are no visual or behavioral changes introduced by this update.

Add some CSS classes for easy custom overrides

---

README.md
src/assets/schemas/config.schema.json
src/common/models/config.model.ts
src/components/page/page.comp.tsx
src/locales/en.json

Implements #285 
This PR introduces two new properties for custom actions:
- `suppressDialog`: Skip the form popup and execute action immediately
- `requireConfirmation`: Show the browser confirmation dialog before executing
This allows for simpler user interactions when no input fields are needed - instead of showing an empty form dialog, the action can be executed directly from the UI. Common use cases include simple state changes like archive/unarchive, enable/disable, etc.

Add option to suppress formdialog for customactions

---

README.md
src/assets/schemas/config.schema.json
src/common/models/config.model.ts
src/common/models/notification.types.ts
src/components/app.tsx
src/components/auth/changePasswortPage/changePasswortPage.comp.tsx
src/components/auth/changePasswortPage/changePasswortPage.scss
src/components/auth/loginPage/loginPage.comp.tsx
src/components/auth/loginPage/loginPage.scss
src/components/formPopup/formPopup.comp.tsx
src/components/formPopup/formPopup.scss
src/components/formRow/formRow.comp.tsx
src/components/navigation/navigation.comp.tsx
src/components/notificationBanner/notificationBanner.comp.tsx
src/components/notificationBanner/notificationBanner.scss
src/components/page/page.comp.tsx
src/locales/en.json
src/services/notification.service.ts

Implement #296 
Adds `notificationStyle` config option with "toast" (default) or "banner" modes.
Introduces a centralized notificationService for managing notifications.
- "toast": current floating top-center behavior
- "banner": fixed, persistent notifications (above tables/cards or inside forms) until navigation/refresh
Note: Please consider merging #299 first. This PR will need to be updated to resolve any conflicts.

Add notificationStyle (toast/banner) option and centralized notification service
