- src/app/services/configuraion.service.ts
Added support for remote URL fetched configuration
In the config.json file, add the following property on the root node:
"remoteUrl" : "https://raw.githubusercontent.com/avihaymenahem/RESTool/master/src/config-sample.json"
**Remote Url property overrides the local config.json file!**
> Added support for remote URL fetched configuration

- README.md
- src/app/components/main-view/get/get.component.html
- src/app/components/main-view/get/get.component.ts
- src/app/services/requests.service.ts
* Enable display value when doing a select box
* Enable paramenters to be in URL instead just at the end as query
parameters
> Add configuration features

- src/app/app.component.ts
This updates the title of the page based on the config, which is helpful when someone has multiple tabs open.
> Change page title to match name in config.json

- src/styles/_purecss.scss
This should prevent the text from being cut off inside select boxes
> Fix padding in select boxes

- README.md
ng build -prod -> ng build --prod
Fix typos.
> Fix typos in docu.

- README.md
- src/app/services/requests.service.ts
- src/config-sample.json
* Added baseUrl as an optional parameter to reduce duplication in each method
> Added a baseUrl parameter to reduce duplication

- src/app/components/input/field-input.component.scss
- src/app/components/main-view/get/get.component.scss
A little css tweak so that the select boxes are the same width as (and styled similarly to) the other controls on the post / put / get pages.
> fix width of select box

- README.md
- src/app/components/input/field-input.component.html
- src/app/components/input/field-input.component.scss
- src/app/components/main-view/get/get.component.html
- src/app/components/main-view/get/get.component.scss
A few more small features:
* a truncate option for the get page
* a fix to prevent the edit / delete button from stacking on top of each other
* a textarea field type for multi-line text
* a note field to add helpful text to put/post pages
> A couple new field types and truncation on get page

- src/components/formPopup/formPopup.comp.tsx
> Fixing issue #87

- src/components/filterField/filterField.comp.tsx
- src/components/filterField/filterField.scss
- src/components/page/page.comp.tsx
> Adding support for "filterable" property. Fixing issue #88

- README.md
The implementation does not allow for strings, only for an array of strings. If a string is passed, every char is iterated and tried for.
> reflect implementation

- src/services/http.service.ts
custom errors where previously always ignored.
> fixed custom error messages

- .gitignore
- README.md
- src/components/app.tsx
- src/services/config.service.ts
- adding option to load dynamic .js config
- fix support for remoteConfig
> dynamic config

- src/common/models/config.model.ts
- src/components/formRow/formRow.comp.tsx
- src/components/formRow/formRow.scss
> Support for date field

- README.md
- package-lock.json
- package.json
- src/assets/schemas/config.schema.json
- src/components/app.context.ts
- src/components/app.tsx
- src/services/config.service.ts
Feature asked in #73.
Not sure if the schema should have `"additionalProperties": false` to help users realize when a field name was mistyped or if it's too constraining for when the schema might not be up to date with the code.
> Configuration JSON schema

- README.md
- src/assets/schemas/config.schema.json
- src/common/models/config.model.ts
- src/components/cards/cards.comp.tsx
- src/components/formPopup/formPopup.comp.tsx
- src/components/formRow/formRow.comp.tsx
- src/components/page/page.comp.tsx
- src/components/popup/popup.comp.tsx
- src/components/table/table.comp.tsx
PR for #116.
Added possibility to configure all button titles, form titles and placeholders throughout the application. Also added the possibility to choose specific form titles within a page as well as a specific "+ Add Item" button text.
> Added possibility to customize labels throughout the application

- src/services/config.service.ts
Make config path relative to `index.html`.
This allows serving the project from a non-root path.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsternlicht/restool/137)
> config: relative to index.html

- .gitignore
- src/common/models/config.model.ts
- src/components/formPopup/formPopup.comp.tsx
- src/components/page/page.comp.tsx
> Added support to plain text on getSingle and queryParams on post

- README.md
- src/assets/schemas/config.schema.json
- src/common/models/config.model.ts
- src/components/formPopup/formPopup.comp.tsx
Here's a PR to add the same kind of `dataTransform` functionality that we have for `getAll` requests.
Here's my use-case: https://github.com/dsternlicht/RESTool/issues/160
The documentation I added here is just a slightly edited copy-paste from the other `dataTransform` documentation. I kinda feel like it's redundant, but I added it for the sake of completeness.
> Data transform get single

- README.md
- src/assets/schemas/config.schema.json
- src/common/models/config.model.ts
- src/components/cards/cards.scss
Allow the user to customize the color of the cards through cardBackground
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> add cardBackground

- src/components/cards/cards.comp.tsx
- src/components/table/table.comp.tsx
> Add support for object and array fields to be rendered in the list view

- README.md
This fix is meant to clarify the multiselect usage by updtaing the corresponding README sections
> Fixes issue #237: upd README on multiselect handling

- README.md
- src/assets/schemas/config.schema.json
- src/common/models/config.model.ts
- src/components/formPopup/formPopup.comp.tsx
- src/components/page/page.comp.tsx
> Make success messages customizable via configs customLabels
